# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - '&f┏                                            ┓'
  - '  server name'
  - ''
  - '&f&lПриветствую, &4%player_name%!'
  - ''
  footer:
  - ''
  - '&fТПС: &2%tps% &7| &fПинг: &2%player_ping%'
  - ''
  - '  &fРежим &#873535&lɢ&#a62e2e&lʀ&#bd2626&lɪ&#d11717&lᴇ&#db0909&lꜰ'
  - '  &fОнлайн: &7(&4%online%&7)'
  - '&f┗                                             ┛'
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
playerlist-objective:
  enabled: true
  value: '%ping%'
  fancy-value: '&7Ping: %ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  fancy-display-players: '&c%health%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard-1.20.3+:
      title: '&#1e0097&ls&#260ba2&lᴇ&#2d15ae&lʀ&#3520b9&lᴠ&#3d2bc4&lᴇ&#4435d0&lʀ &#4c40db&lɴ&#544be6&lᴀ&#5b55f2&lᴍ&#6360fd&lᴇ'
      display-condition: '%player-version-id%>=765'
      lines:
        - '&#1e0097&lɪ&#3520b9&lɴ&#4c40db&lꜰ&#6360fd&lᴏ'
        - ''
        - '&fНик: &1%player_name%'
        - 'Привелегия: &1%luckperms-prefix%'
        - '&#1e0097&ls&#2f18b1&lᴛ&#4130ca&lᴀ&#5248e4&lᴛ&#6360fd&ls'
        - ''
        - '&fБаланс: &1%vault_eco_balance%'
        - '&fРублей: &1%playerpoints_points%'
        - '&fУ/С: &1%statistic_player_kills%&7/&1%statistic_deaths%'
    scoreboard:
      title: '&#450000s&#510000e&#5D0000r&#690000v&#750000e&#800000r &#8C0000n&#980000a&#A40000m&#B00000e'
      lines:
        - ' &#24A700ɪ&#238C08ɴ&#23710Fꜰ&#225617ᴏ'
        - '• &fНик: &4%player_name%'
        - '• &fПривелегия: &4%luckperms-prefix%'
        - '• &fТитул: %luckperms-suffix%'
        - ''
        - ' &#24A700s&#249306ᴛ&#237F0Cᴀ&#236A11ᴛ&#225617s'
        - ''
        - '• &fБаланс: '
        - '• &fРублей: &4%playerpoints_points%'
        - '• &fНаиграно: &4%statistic_hours_played%'
        - '• &fУ/С: &4%statistic_player_kills%&7/&4%statistic_deaths%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
