Warp:
  Creation:
    # A list of worlds, where players can't create warps.
    # This setting can be bypassed with the 'su.nexmedia.engine.api.server.JPermission@691dafb1' permission.
    World_Blacklist:
    - other_world_123
    - special_world
    # Amount of possible warps to create for certain permission groups.
    # If player is in multiple groups listed here, the greater value will be used.
    # If player is not in any group listed here, the 'default' value will be used if present.
    # -*-
    # If you want to use this based on player's permissions rather than groups, you can do so by
    # giving 'sunlight.warps.amount.[name]' permission, where '[name]' is name from this list.
    # Make sure to use names that are different to your permission groups. Otherwise they will be overriden.
    # -*-
    # Use '-1' for unlimited warps amount.
    # You must have Vault installed for this feature to work. No extra permissions required.
    Amount_Per_Rank:
      admin: -1
      moderator: 3
  Description:
    # Sets the maximal text length for a warp description.
    # This setting can be bypassed with the 'sunlight.warps.bypass.description.size' permission.
    MaxSize: 40
