Inventory_Split:
  # Enables Inventory Split feature for different inventories per world.
  Enabled: false
  # List of Inventory Types that are affected by the Split feature.
  # Allowed values: ENDER_CHEST, PLAYER
  Affected_Inventories:
  - ENDER_CHEST
  - PLAYER
  # List of custom world groups, that will share the same inventories in that worlds.
  World_Groups:
    survival:
    - world
    - world_nether
    - world_the_end
    creative:
    - world_creative
Command_Blocker:
  # Sets whether or not certain commands should be blocked in specified worlds.
  Enabled: false
  # List of worlds and commands that will be disabled in that worlds.
  # This can be bypassed with 'sunlight.worlds.bypass.commands' permission.
  # You only need to put one alias for each command. It will auto-detect all other aliases and block them too.
  World_Commands:
    world_custom:
    - fly
    - god
# List of worlds, where players can not fly.
# This can be bypassed with 'sunlight.worlds.bypass.fly' permission.
NoFlyWorlds:
- world2
- world1
AutoWipe:
  Notification:
    # Sets whether or not players will get a notification about upcoming world auto-reset.
    Enabled: true
    # Sets minimal threshold (in seconds) for notifications to work.
    # When next world's auto-reset time left (in seconds) is smaller or equals to this amount, notification will start to appear.
    # [Default is 86400 (1 day)]
    Threshold: 86400
    # Sets world's auto-reset notifications interval (in seconds).
    # [Default is 3600 (1 hour)]
    Interval: 3600
  MovePlayersOut:
    ToSpawn:
      # Sets whether or not players will be teleported to specified Spawn point when world is about to auto-reset.
      # If disabled, players will be teleported to the first available world.
      # [Requires Spawns module to be enabled]
      Enabled: false
      # Defines which Spawn point will be used to teleport players from a world before auto-reset.
      # If invalid Spawn point provided, players will be teleported to the first available world.
      # [Requires Spawns module to be enabled]
      Name: default
