Plugin:
  # Command names that will be registered as main plugin commands.
  # Do not leave this empty. Split multiple names with a comma.
  Command_Aliases: sunlight,sl
  # Localized plugin name. It's used in messages and with internal placeholders.
  Name: SunLight
  # Plugin prefix. Used in messages.
  # You can use %plugin_name_localized% placeholder for a plugin name.
  Prefix: '#fdf35e%plugin_name%#d4d9d8 » '
  # Sets the plugin language.
  # It will use language config from the '/lang/' sub-folder for specified language code.
  # By default uses your system's default locale.
  Language: ru

Database:
  # Table prefix to use when plugin create tables. Do not leave this empty.
  Table_Prefix: sunlight
  # Sets database type.
  # Available values: MYSQL,SQLITE
  Type: SQLITE
  # Defines how often (in minutes) user data of online players will be saved to the database.
  # Set -1 to disable.
  Auto_Save_Interval: 20
  # Defines how often (in seconds) plugin data will be fetched and loaded from the remote database.
  Sync_Interval: -1
  MySQL:
    # Database user name.
    Username: root
    # Database user password.
    Password: root
    # Database host address. Like http://127.0.0.1:3306/
    Host: localhost:3306
    # MySQL database name, where plugin tables will be created.
    Database: minecraft
  SQLite:
    # File name for the database file.
    # Actually it's a path to the file, so you can use directories here.
    FileName: data.db
  Purge:
    # Enables/Disables purge feature.
    # Purge will remove all records from the plugin tables that are 'old' enough.
    Enabled: false
    # Sets maximal 'age' for the database records before they will be purged.
    # This option may have different behavior depends on the plugin.
    # By default it's days of inactivity for the plugin users.
    For_Period: 60
General:
  # Sets the global date format used in various plugin modules.
  Date_Format: dd/MM/yyyy HH:mm
  # Sets the global time format used in various plugin modules.
  Time_Format: HH:mm:ss
Modules:
  bans: true
  worlds: true
  spawns: true
  homes: true
  kits: true
  warps: true
  chat: false
  tab: false
  scoreboard: false
  rtp: false
  extras: true
  afk: true
