Database:
  # Sets database type.
  # Available values: MYSQL,SQLITE
  Type: SQLITE
  # Table prefix to use when plugin create tables. Do not leave this empty.
  Table_Prefix: sunlight_bans
  SQLite:
    # File name for the database file.
    # Actually it's a path to the file, so you can use directories here.
    FileName: bans.db
  # Defines how often (in minutes) user data of online players will be saved to the database.
  # Set -1 to disable.
  Auto_Save_Interval: 20
  # Defines how often (in seconds) plugin data will be fetched and loaded from the remote database.
  Sync_Interval: -1
  MySQL:
    # Database user name.
    Username: root
    # Database user password.
    Password: root
    # Database host address. Like http://127.0.0.1:3306/
    Host: localhost:3306
    # MySQL database name, where plugin tables will be created.
    Database: minecraft
  Purge:
    # Enables/Disables purge feature.
    # Purge will remove all records from the plugin tables that are 'old' enough.
    Enabled: false
    # Sets maximal 'age' for the database records before they will be purged.
    # This option may have different behavior depends on the plugin.
    # By default it's days of inactivity for the plugin users.
    For_Period: 60
General:
  # A list of player names/IP addresses that will be immune to all punishments.
  Immunies:
  - 127.0.0.2
  - admin_name
  # Custom shortcuts/aliases for the time units.
  # Example: When punishing, you specify duration as '60min', in this case '60' is amount, 'min' is time alias (minutes).
  Time_Aliases:
    WEEKS: w
    MONTHS: mon
    DAYS: d
    SECONDS: s
    YEARS: y
    HOURS: h
    MINUTES: min
  # A list of all possible reasons for punishments.
  # Use 'default' keyword for a default reason (when none specified).
  Reasons:
    grief:
      Message: Оскорбление
    toxic:
      Message: Токсичное поведение
    default:
      Message: Нарушение правил
    advertisement:
      Message: Реклама других серверов/сайтов
  DisconnectInfo:
    # Text to display for player in disconnect window when kicked.
    Kick:
    - '&c&nВас исключили с сервера!'
    - '&7'
    - '&cПричина: &e%punishment_reason%'
    - '&cАдминистратор: &e%punishment_punisher%'
    Ban:
      # Text to display for player in disconnect window when kicked.
      Permanent:
      - '&cВы забанены на этом сервере!'
      - '&7'
      - '&7Забанен: &f%punishment_date_created%'
      - '&7Администратор: &f%punishment_punisher%'
      - '&7Причина: &f%punishment_reason%'
      - '&7'
      - '&eВы забанены навсегда!'
      - '&7Обжалуйте на: &f&nhttps://discord.gg/3fh5xyfqHs'
      # Text to display for player in disconnect window when kicked.
      Temp:
      - '&cВы забанены на этом сервере!'
      - '&7'
      - '&7Забанен: &f%punishment_date_created%'
      - '&7Администратор: &f%punishment_punisher%'
      - '&7Причина: &f%punishment_reason%'
      - '&7Разбан через: &f%punishment_expires_in%'
      - '&7'
      - '&7Обжалуйте на: &f&nhttps://discord.gg/3fh5xyfqHs'
Punishments:
  Mute:
    # A list of commands that will be blocked for muted players.
    Blocked_Commands:
    - me
    - tell
    - broadcast
  Rank:
    # A list of rank based duration limits for each punishment type.
    # (You must have Vault installed for this feature to work)
    # This will prevent players to punish others for a time longer than you set here.
    # Player permission groups will be auto-deetected
    # The greatest duration limit will be used if player has multiple ranks with duration limits.
    # To remove limit for certain punishment type, set its 'Duration' to -1.
    # To remove all limits, give 'sunlight.bans.bypass.duration.limit' permission.
    Duration_Limit:
      helper:
        MUTE:
          Amount: 1
          TimeUnit: DAYS
        BAN:
          Amount: 2
          TimeUnit: WEEKS
        WARN:
          Amount: 3
          TimeUnit: WEEKS
      moderator:
        MUTE:
          Amount: 1
          TimeUnit: WEEKS
        BAN:
          Amount: 2
          TimeUnit: MONTHS
        WARN:
          Amount: 3
          TimeUnit: MONTHS
    # --- [BETA FEATURE] ---
    # This feature is not perfect and requires improvements.
    #  
    # Here you can set priority for each rank.
    # Players with greatest ranks can not be punished by ones with lowest ranks.
    # Use 'default' keyword for all ranks not listed here.
    Priority:
      default: 0
      helper: 1
      moderator: 2
      admin: 1000
  Warn:
    # How many warns player can receive before they all will be auto expired?
    # Set this to -1 for unlimit.
    Max_Amount: 5
    # A list of commands to be executed when player got certain amount of warnings.
    # Commands get executed from the server console.
    # Use '%player_name%' placeholder for a player name.
    Auto_Commands:
      '5':
      - kick %player_name%
      '3':
      - mute %player_name% 15min
