# Sets the default world if RTP is not available in player's world.
Default_World: world
# Sets whether or not RTP will search location in Default World, if no ranges are available in the current one.
Force_To_Default: true
LocationSearch:
  # Amount of RTP attempts to get a valid teleport location.
  Attempts: 5
  # Sets whether or not only chunks that have already been generated will be used when searching for a teleport location.
  # NOTE: Works only for 1.19.4 or above!
  Generated_Chunks_Only: true
  # Sets whether or not only chunks that have been loaded by players will be used when searching for a teleport location.
  # NOTE: Settings this on 'true' may result in a lot of failures when server lacks online players.
  Loaded_Chunks_Only: false
  # List of per-world range values to search location in.
  # You can create as many entries per world as you want.
  # Put here your ACTUAL worlds, especially if your main world is named differently than default 'world'.
  Ranges:
    world:
      default:
        Start_X: 0
        Start_Z: 0
        Distance_Min: 500
        Distance_Max: 2500
        Directions:
        - NORTH
        - WEST
        - EAST
        - SOUTH
