Use_Mini_Message: false
# ==================== GUI CONTENT ====================
# You can freely edit items in this section as you wish (add, remove, modify items).
# Get some tips in documentation: https://github.com/nulli0n/NexEngine-spigot/wiki/Menu-Config
# The following values are available for button types:
# - DENY_CONVERSATIONS
# - DENY_TELEPORTS
# - HIDE_CHAT
# - RETURN
# ==================================================
Content:
  return:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmU5YWU3YTRiZTY1ZmNiYWVlNjUxODEzODlhMmY3ZDQ3ZTJlMzI2ZGI1OWVhM2ViNzg5YTkyYzg1ZWE0NiJ9fX0=
      Name: '#e6e4dd(↓) &fВернуться'
      Lore: []
    Slots: 31
    Type: RETURN
  
  chat:
    Item:
      Material: MAP
      Name: '#ee9aff&lСкрыть чат'
      Lore:
      - '#ee9aff▪ #ddeceeВключено: #ee9aff%hide_chat%'
      - ''
      - '#ddeceeСкрывает все сообщения в чате'
      - '#ddeceeот этого игрока, если включено.'
      - ''
      - '#9af7ff&lДействия:'
      - '#9af7ff▪ #ddeceeЛевый клик: #9af7ffПереключить'
    Slots: 10
    Type: HIDE_CHAT
  
  private_messages:
    Item:
      Material: WRITABLE_BOOK
      Name: '#ee9aff&lЗапретить ЛС'
      Lore:
      - '#ee9aff▪ #ddeceeВключено: #ee9aff%deny_conversations%'
      - ''
      - '#ddeceeБлокирует все личные сообщения'
      - '#ddeceeот этого игрока, если включено.'
      - ''
      - '#9af7ff&lДействия:'
      - '#9af7ff▪ #ddeceeЛевый клик: #9af7ffПереключить'
    Slots: 13
    Type: DENY_CONVERSATIONS
  
  teleport_requests:
    Item:
      Material: ENDER_PEARL
      Name: '#ee9aff&lЗапретить ТП'
      Lore:
      - '#ee9aff▪ #ddeceeВключено: #ee9aff%deny_teleports%'
      - ''
      - '#ddeceeБлокирует все запросы на телепортацию'
      - '#ddeceeот этого игрока, если включено.'
      - ''
      - '#9af7ff&lДействия:'
      - '#9af7ff▪ #ddeceeЛевый клик: #9af7ffПереключить'
    Slots: 16
    Type: DENY_TELEPORTS
Settings:
  # Sets the GUI title.
  Title: '#5d6d7e&l      Настройки игнора'
  # Sets the GUI size. Must be multiply of 9.
  # Useful for 'CHEST' Inventory Type only.
  Size: 36
  # Sets the GUI type.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
  Inventory_Type: CHEST
  # Sets the GUI auto-refresh interval (in seconds). Set this to 0 to disable.
  Auto_Refresh: 0
